export const CELESTIAL_TIERS = [
  {
    tier: 1,
    name: "Asteroid",
    color: "#78716c",
    glow: "#a8a29e",
    points: "10 pts",
    badge: "Tier 1",
    desc: "Craggy dark basalt rock with 3 crater pits and molten mineral veins.",
  },
  {
    tier: 2,
    name: "Moon",
    color: "#94a3b8",
    glow: "#cbd5e1",
    points: "25 pts",
    badge: "Tier 2",
    desc: "Silvery lunar regolith with basalt maria seas and rayed impact craters.",
  },
  {
    tier: 3,
    name: "Terrestrial (Earth)",
    color: "#38bdf8",
    glow: "#0284c7",
    points: "50 pts",
    badge: "Tier 3",
    desc: "Deep azure oceans, emerald landmasses, polar ice caps, swirling clouds.",
  },
  {
    tier: 4,
    name: "Gas Giant (Jupiter)",
    color: "#fb923c",
    glow: "#ea580c",
    points: "100 pts",
    badge: "Tier 4",
    desc: "Turbulent storm belts and the iconic swirling Great Red Spot storm vortex.",
  },
  {
    tier: 5,
    name: "Ringed Giant (Saturn)",
    color: "#facc15",
    glow: "#ca8a04",
    points: "250 pts",
    badge: "Tier 5",
    desc: "Golden gas sphere encircled by dual 3D perspective accretion rings.",
  },
  {
    tier: 6,
    name: "Ice Giant",
    color: "#2dd4bf",
    glow: "#0d9488",
    points: "500 pts",
    badge: "Tier 6",
    desc: "Crystalline turquoise glacial facets with neon cyan polar auroral crowns.",
  },
  {
    tier: 7,
    name: "Red Dwarf",
    color: "#f87171",
    glow: "#dc2626",
    points: "1,000 pts",
    badge: "Tier 7",
    desc: "Convective solar granules and dynamic arching coronal prominences.",
  },
  {
    tier: 8,
    name: "Blue Supergiant",
    color: "#60a5fa",
    glow: "#2563eb",
    points: "2,500 pts",
    badge: "Tier 8",
    desc: "White-hot thermonuclear plasma core with 8 radiant starburst rays.",
  },
  {
    tier: 9,
    name: "Pulsar (Magnetar)",
    color: "#c084fc",
    glow: "#9333ea",
    points: "5,000 pts",
    badge: "Tier 9",
    desc: "Ultra-dense violet neutron core with dual rotating relativistic jets.",
  },
  {
    tier: 10,
    name: "Singularity",
    color: "#a855f7",
    glow: "#ec4899",
    points: "10,000 pts",
    badge: "Apex",
    desc: "Event horizon encircled by Einstein photon ring & violet Doppler disk.",
  },
];
